const OrderActionTypes = {
	CREATE_ORDER_START: 'CREATE_ORDER_START',
	FETCH_USER_ORDERS_START: 'FETCH_USER_ORDERS_START',
	FETCH_USER_ORDERS_SUCCESS: 'FETCH_USER_ORDERS_SUCCESS',
	FETCH_ORDERS_START: 'FETCH_ORDERS_START',
	FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
	FETCH_STATES_START: 'FETCH_STATES_START',
	FETCH_STATES_SUCCESS: 'FETCH_STATES_SUCCESS',
	FETCH_CITIES_START: 'FETCH_CITIES_START',
	FETCH_CITIES_SUCCESS: 'FETCH_CITIES_SUCCESS',
}

export default OrderActionTypes