const UserActionTypes = {
	SIGN_IN_WITH_FACEBOOK_START: 'SIGN_IN_WITH_FACEBOOK_START',
	SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	LOGOUT: 'LOGOUT',
}

export default UserActionTypes