const UserActionTypes = {
	SIGN_IN_WITH_FACEBOOK_START: 'SIGN_IN_WITH_FACEBOOK_START',
	SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	LOGOUT: 'LOGOUT',
	INSERT_CONFIRMATION_START: 'INSERT_CONFIRMATION_START',
	FETCH_CONFIRMATIONS_START: 'FETCH_CONFIRMATIONS_START',
	FETCH_CONFIRMATIONS_SUCCESS: 'FETCH_CONFIRMATIONS_SUCCESS',
}

export default UserActionTypes