const UserActionTypes = {
	SIGN_IN_WITH_FACEBOOK_START: 'SIGN_IN_WITH_FACEBOOK_START',
	SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	LOGOUT: 'LOGOUT',
	INSERT_SONG_REQUEST_START: 'INSERT_SONG_REQUEST_START',
	FETCH_SONG_REQUESTS_START: 'FETCH_SONG_REQUESTS_START',
	FETCH_SONG_REQUESTS_SUCCESS: 'FETCH_SONG_REQUESTS_SUCCESS',
}

export default UserActionTypes