const ProductActionTypes = {
	INSERT_PRODUCT_START: 'INSERT_PRODUCT_START',
	FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
	FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
}

export default ProductActionTypes